[build]
builder = "nixpacks"

[build.nixpacksConfig]
phases.build.cmds = ["mvn clean package -DskipTests"]

[deploy]
startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/demo-1.0.0.jar"

[environment]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"