[build]
builder = "DOCKERFILE"
watchPatterns = ["src/**", "Dockerfile"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = "300s"
restartPolicyType = "ON_FAILURE"

[environment]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"
JAVA_VERSION = "17"