spring:
  application:
    name: iPhone Store Management System
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Database configuration for Railway
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://shinkansen.proxy.rlwy.net:18598/railway?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF8}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:RPBPxQJOaCvkgwBjmZulhkjQLaBkWjiJ}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf8
          CharSet: utf8
          useUnicode: true

  # Thymeleaf Configuration
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # Security Configuration
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    root: INFO
    com.idat.continua2.demo: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never